site_name: Music AI Vault
site_url: https://pi-kay.github.io/Music-AI-Vault/
repo_url: https://github.com/Pi-Kay/Music-AI-Vault
repo_name: Pi-Kay/Music-AI-Vault

theme:
  name: material
  features:
    - navigation.tabs
    - search

nav:
  - Home: index.md  # Rename your main MD to index.md if needed
  - Guidelines: Music AI Document.md  # Adjust to match your file names
